# Generated by Django 3.1.4 on 2020-12-25 06:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Position Title name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Position description')),
                ('senority', models.CharField(choices=[('INTERN', 'Internship'), ('ENTRY', 'Entry-Level'), ('ASSOCIATE', 'Associate'), ('SENIOR', 'Senior'), ('DIRECTOR', 'Director')], default='ENTRY', max_length=10, verbose_name='Senority')),
                ('jobtype', models.CharField(choices=[('FULL', 'Full-time'), ('CONTRACT', 'Contract'), ('INTERN', 'Internship'), ('PART_TIME', 'Part-time'), ('TEMP', 'Temporary')], default='FULL', max_length=10, verbose_name='Job-type')),
                ('neededSkills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Skill-tags'), blank=True, null=True, size=None)),
                ('industry', models.CharField(max_length=50, verbose_name='Industry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='company-posted-job')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
    ]
