# Generated by Django 3.1.4 on 2020-12-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forumType', models.CharField(choices=[('ENGINEER', 'Engineer'), ('BUSINESS', 'Business'), ('DESIGN', 'Design')], max_length=10)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Forum-descriptions')),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
            },
        ),
    ]
