# Generated by Django 3.1.4 on 2020-12-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='senority',
            field=models.CharField(blank=True, choices=[('INTERN', 'Internship'), ('ENTRY', 'Entry-Level'), ('ASSOCIATE', 'Associate'), ('SENIOR', 'Senior'), ('DIRECTOR', 'Director')], default='INTERN', max_length=10, null=True, verbose_name='Senority'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
