# Generated by Django 3.1.4 on 2020-12-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201226_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
